version: '3.8'
services:
  api:
    image: backend-django:latest
    container_name: django-admin
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=${DEBUG}
        - NAME=${NAME}
        - USER=${USER}
        - PASSWORD=${PASSWORD}
        - HOST=${HOST}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - NAME=${NAME}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - build_backend:/backend/staticfiles
  web:
    image: frontend-react:latest
    container_name: my-pokemon-web
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "8000:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - build_backend:/vol/static
    depends_on:
      - api
volumes:
  build_backend:


